### ISSUE TITLE
Minecraft 1.20.6 Requires openjdk21-jre

### ISSUE THREAD

**Issue by hyper10110** [tschettervictor/truenas-iocage-mineos#3]
Can't start Minecraft servers using version 1.20.6.  Apparently, it needs a newer version of Java

**Comment by tschettervictor** [comment]
I think the issue might be that I use yarn now instead of node to install it. There was recently an issue when node16 became EOL, and it doesn’t install when using any node version other than node16.

So I switched to using yarn because it installs it fine, but it looks like it might now be able to start servers properly.

**Comment by tschettervictor** [comment]
There is no package available for openjdk21-jre so im now using openjdk22

Can you check if this works for you?

**Comment by hyper10110** [comment]
Yeah sorry I got the package name wrong, in any case I had manually updated the jail to openjdk21 and it fixed the problem.  So then I altered your script to add openjdk22

# List packages to be auto-installed after jail creation
cat <<__EOF__ >/tmp/pkg.json
{
  "pkgs": [
  "git-lite",
  "gmake",
  "openjdk22",
  "npm-node20",
  "node20",
  "yarn-node20",
  "python39",
  "py39-rdiff-backup",
  "py39-supervisor",
  "rsync",
  "screen"
  ]
}
__EOF__

and it still runs fine.

Thanks for your work on this its very handy
